# Generated by Django 5.1.3 on 2024-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
